# Generated by Django 3.0.3 on 2020-07-13 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ida_core', '0003_database_datasetfamily'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessAchievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AccessModeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AccessMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('access_achievements', models.ManyToManyField(to='ida_core.AccessAchievement')),
                ('access_mode_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ida_core.AccessModeCategory')),
                ('dataset_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ida_core.DatasetFamily')),
            ],
        ),
        migrations.AddField(
            model_name='consumer',
            name='access_achievements',
            field=models.ManyToManyField(to='ida_core.AccessAchievement'),
        ),
    ]
