# Generated by Django 3.0.3 on 2020-07-14 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ida_core', '0004_auto_20200713_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessModeAnonymization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AccessModeResearchField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AccessModeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='accessmode',
            name='access_mode_category',
        ),
        migrations.DeleteModel(
            name='AccessModeCategory',
        ),
        migrations.AddField(
            model_name='accessmode',
            name='access_mode_anonymization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ida_core.AccessModeAnonymization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accessmode',
            name='access_mode_research_field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ida_core.AccessModeResearchField'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accessmode',
            name='access_mode_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ida_core.AccessModeType'),
            preserve_default=False,
        ),
    ]
