# Generated by Django 3.0.3 on 2020-07-27 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ida_core', '0006_auto_20200715_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRegime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='accessmode',
            name='dataset_family',
        ),
        migrations.AddField(
            model_name='accessmode',
            name='access_regime',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ida_core.AccessRegime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasetfamily',
            name='access_regime',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ida_core.AccessRegime'),
            preserve_default=False,
        ),
    ]
