# Generated by Django 3.0.3 on 2020-07-27 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ida_core', '0007_auto_20200727_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('project_lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ida_core.Consumer')),
            ],
        ),
        migrations.AddField(
            model_name='accessregime',
            name='description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProjectGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_mode_anonymization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ida_core.AccessModeAnonymization')),
                ('access_mode_research_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ida_core.AccessModeResearchField')),
                ('access_mode_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ida_core.AccessModeType')),
                ('data', models.ManyToManyField(to='ida_core.DatasetFamily')),
                ('members', models.ManyToManyField(to='ida_core.Consumer')),
                ('projct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ida_core.Project')),
            ],
        ),
    ]
