# Generated by Django 3.0.3 on 2020-07-27 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ida_core', '0008_auto_20200727_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectgroup',
            old_name='projct',
            new_name='project',
        ),
    ]
