# Generated by Django 3.0.3 on 2020-07-29 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ida_core', '0011_auto_20200728_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='access_achievements',
        ),
        migrations.AddField(
            model_name='accessachievement',
            name='isLinkedToConsumer',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accessachievement',
            name='isLinkedToProject',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AchievementRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='ida_core.Consumer')),
                ('project', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='ida_core.Project')),
            ],
        ),
    ]
