# Generated by Django 3.0.3 on 2020-07-29 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ida_core', '0012_auto_20200729_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessachievement',
            name='isLinkedToConsumer',
            field=models.BooleanField(verbose_name='always linked to a specific consumer'),
        ),
        migrations.AlterField(
            model_name='accessachievement',
            name='isLinkedToProject',
            field=models.BooleanField(verbose_name='always linked to a specific project'),
        ),
        migrations.AlterField(
            model_name='achievementrelation',
            name='consumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ida_core.Consumer'),
        ),
        migrations.AlterField(
            model_name='achievementrelation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ida_core.Project'),
        ),
    ]
