# Generated by Django 3.0.3 on 2020-07-29 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ida_core', '0013_auto_20200729_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievementrelation',
            name='achievement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ida_core.AccessAchievement'),
        ),
    ]
