# Generated by Django 3.0.3 on 2020-08-21 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ida_core', '0015_auto_20200730_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataLab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ida_core.Project')),
            ],
        ),
    ]
